# This rule is not used by the project ai-diagnostic-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over diagnostic.sre.example.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ai-diagnostic-operator
    app.kubernetes.io/managed-by: kustomize
  name: poddiagnosis-admin-role
rules:
- apiGroups:
  - diagnostic.sre.example.com
  resources:
  - poddiagnoses
  verbs:
  - '*'
- apiGroups:
  - diagnostic.sre.example.com
  resources:
  - poddiagnoses/status
  verbs:
  - get
