# This rule is not used by the project ai-diagnostic-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the diagnostic.sre.example.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ai-diagnostic-operator
    app.kubernetes.io/managed-by: kustomize
  name: poddiagnosis-editor-role
rules:
- apiGroups:
  - diagnostic.sre.example.com
  resources:
  - poddiagnoses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - diagnostic.sre.example.com
  resources:
  - poddiagnoses/status
  verbs:
  - get
