apiVersion: diagnostic.sre.example.com/v1
kind: PodDiagnosis
metadata:
  labels:
    app.kubernetes.io/name: ai-diagnostic-operator
    app.kubernetes.io/managed-by: kustomize
  name: poddiagnosis-sample
spec:
  # TODO(user): Add fields here
